### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by jpuck** [csabapalfi/github-markdown-html#11]
npm version 4.2.0
node version 7.8.0

package does not seem to install

    $ npm install github-markdown-html

> npm ERR! cb() never called!

**Comment by csabapalfi** [comment]
Confirmed this on node 7.10 with npm@4.2.0 but I can't reproduce on node 8 + npm 5.

Looks like there's an open issue on npm that looks very similar: https://github.com/npm/npm/issues/15344#issuecomment-304531892

Will try looking into this a bit more later but in the meantime I suggest using yarn or upgrading npm.

**Comment by hlin117** [comment]
It looks like `package.json` is needed, according to [this comment](https://github.com/npm/npm/issues/15344#issuecomment-312634027).

**Comment by csabapalfi** [comment]
Hi, I'll close this now. Please re-open if there are any issues still.
